# Generated by Django 4.2.1 on 2023-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SADuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=100)),
                ("Phone", models.CharField(max_length=10)),
                (
                    "totalamount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
