# Generated by Django 4.2.1 on 2023-08-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0003_rename_phone_saduser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="saduser",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="user", name="year", field=models.IntegerField(null=True),
        ),
    ]
