# Generated by Django 4.2.1 on 2023-08-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0005_remove_user_date_remove_user_year"),
    ]

    operations = [
        migrations.RemoveField(model_name="saduser", name="date",),
    ]
