# Generated by Django 4.2.1 on 2023-08-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0006_remove_saduser_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="SADTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "withdraw",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="WPBLAPP.user"
                    ),
                ),
            ],
        ),
    ]
