# Generated by Django 4.2.1 on 2023-08-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0007_sadtransaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sadtransaction", old_name="userid", new_name="usernum",
        ),
    ]
