# Generated by Django 4.2.1 on 2023-08-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0008_rename_userid_sadtransaction_usernum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sadtransaction",
            name="usernum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="WPBLAPP.saduser"
            ),
        ),
    ]
