# Generated by Django 4.2.1 on 2023-08-29 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0009_alter_sadtransaction_usernum"),
    ]

    operations = [
        migrations.AddField(
            model_name="saduser",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="user",
            name="date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
