# Generated by Django 4.2.1 on 2023-08-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0010_saduser_date_user_date_user_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="saduser",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
